import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background-base h-screen overflow-hidden`}
      >
        <div className="h-screen px-2 py-6 pb-10 md:p-10 m-0">
          <div className="bg-background h-full rounded-2xl overflow-y-auto flex flex-col items-center w-full justify-center border-4 md:border-8 border-background-base/50">
          {children}
          </div>
        </div>

        <NavBar />
      </body>
    </html>
  );
}
